config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: "/"
  
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'test' && password == 'test'
  end
  mount Sidekiq::Web => '/sidekiq'

  Spree::Core::Engine.add_routes do
    get "/sale" => "home#sale"
    
    namespace :api, defaults: { format: 'json' } do 
      namespace :v1 do 
        resources :clients, only: :index
        resources :user_prices, only: [:index]
      end
    end        
  end

  get '/admin_api_keys', to: 'spree/api/v1/admin_api_keys#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'frontend/homepage#index'


  namespace :admin do
    root to: "homepage#index"
    post 'upload_products_csv', to: 'products#upload_products_csv'
    
    resources :orders, only: [:index, :new, :show, :destroy]

    namespace :customers do
      resources :clients, only: [:index, :create, :show, :update, :destroy]
      # resources :companies, only: [:index, :create]
      resources :addresses, only: [:index, :create, :update, :destroy, :show]
      resources :orders, only: [:index, :update]
    end

    resources :customers do
      resources :companies, only: [:index, :create], controller: "customers/companies"
      resources :subsidiaries, only: [:index, :create], controller: "customers/subsidiaries"
      resources :stores, only: [:index, :create], controller: "customers/stores"
      resources :prices, controller: "customers/prices", only: [:index, :new, :edit, :update, :destroy]
    end

    resources :products, only: [:index, :show, :new, :create, :update] do
      resources :images, only: [:index, :create, :destroy, :show, :update]
      resources :prices, only: [:index, :create, :edit, :new, :destroy, :update]
      resources :stocks, only: [:index, :create, :edit, :new, :destroy, :update]
      resources :variants, only: [:index, :create, :show, :new, :destroy, :update]
      resources :variants_stock, only: [:update]
    end

    resources :option_types, only: [:index, :update, :show, :destroy, :new, :create] do 
      resources :option_values, only: [:create, :destroy, :update]
    end
    match '/option_types/update_position', to: 'option_types#update_option_position', via: :post
  end

  spree_path = Rails.application.routes.url_helpers.try(:spree_path, trailing_slash: true) || '/'
  get Spree.admin_path, to: redirect((spree_path + Spree.admin_path + '/orders').gsub('//', '/')), as: :admin
end

app/controllers/admin/customers/orders_controller.rb
module Admin
  class Customers::OrdersController < Customers::ApplicationController
    helper_method :user 

    def index
      puts params
    end

    def user
      user ||= Spree::User.find(params[:id])
    end
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    helper OrdersHelper

    def index
      params[:q] ||= {}
      params[:q][:completed_at_not_null] ||= '0'
      @show_only_completed = params[:q][:completed_at_not_null] == '1'
      params[:q][:s] ||= @show_only_completed ? 'completed_at desc' : 'created_at desc'
      params[:q][:completed_at_not_null] = '' unless @show_only_completed

      # As date params are deleted if @show_only_completed, store
      # the original date so we can restore them into the params
      # after the search
      created_at_gt = params[:q][:created_at_gt]
      created_at_lt = params[:q][:created_at_lt]

      params[:q].delete(:inventory_units_shipment_id_null) if params[:q][:inventory_units_shipment_id_null] == '0'

      if params[:q][:created_at_gt].present?
        params[:q][:created_at_gt] = begin
                                       Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day
                                     rescue StandardError
                                       ''
                                     end
      end

      if params[:q][:created_at_lt].present?
        params[:q][:created_at_lt] = begin
                                       Time.zone.parse(params[:q][:created_at_lt]).end_of_day
                                     rescue StandardError
                                       ''
                                     end
      end

      if @show_only_completed
        params[:q][:completed_at_gt] = params[:q].delete(:created_at_gt)
        params[:q][:completed_at_lt] = params[:q].delete(:created_at_lt)
      end

      @search = Spree::Order.preload(:user).ransack(params[:q])

      # lazy loading other models here (via includes) may result in an invalid query
      # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
      # see https://github.com/spree/spree/pull/3919
      @orders = @search.result(distinct: true).
                page(params[:page]).
                per(params[:per_page] || Spree::Config[:admin_orders_per_page])

      # Restore dates
      params[:q][:created_at_gt] = created_at_gt
      params[:q][:created_at_lt] = created_at_lt
    end

    def show; end

    def destroy; end

    def create; end

    def new; end
  end
end

# module Spree
#   module Admin
#     class OrdersController < Spree::Admin::BaseController
#       before_action :initialize_order_events
#       before_action :load_order, only: [:edit, :update, :cancel, :resume, :approve, :resend, :open_adjustments, :close_adjustments, :cart, :store, :set_store]

#       respond_to :html

      

#       def new
#         @order = Spree::Order.create(order_params)
#         redirect_to cart_admin_order_url(@order)
#       end

#       def edit
#         can_not_transition_without_customer_info

#         @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?
#       end

#       def cart
#         @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?

#         if @order.shipments.shipped.exists?
#           redirect_to edit_admin_order_url(@order)
#         end
#       end

#       def store
#         @stores = Spree::Store.all
#       end

#       def update
#         if @order.update(params[:order]) && @order.line_items.present?
#           @order.update_with_updater!
#           unless @order.completed?
#             # Jump to next step if order is not completed.
#             redirect_to admin_order_customer_path(@order) and return
#           end
#         else
#           @order.errors.add(:line_items, Spree.t('errors.messages.blank')) if @order.line_items.empty?
#         end

#         render action: :edit
#       end

#       def cancel
#         @order.canceled_by(try_spree_current_user)
#         flash[:success] = Spree.t(:order_canceled)
#         redirect_back fallback_location: spree.edit_admin_order_url(@order)
#       end

#       def resume
#         @order.resume!
#         flash[:success] = Spree.t(:order_resumed)
#         redirect_back fallback_location: spree.edit_admin_order_url(@order)
#       end

#       def approve
#         @order.approved_by(try_spree_current_user)
#         flash[:success] = Spree.t(:order_approved)
#         redirect_back fallback_location: spree.edit_admin_order_url(@order)
#       end

#       def resend
#         OrderMailer.confirm_email(@order.id, true).deliver_later
#         flash[:success] = Spree.t(:order_email_resent)

#         redirect_back fallback_location: spree.edit_admin_order_url(@order)
#       end

#       def open_adjustments
#         adjustments = @order.all_adjustments.finalized
#         adjustments.update_all(state: 'open')
#         flash[:success] = Spree.t(:all_adjustments_opened)

#         respond_with(@order) { |format| format.html { redirect_back fallback_location: spree.admin_order_adjustments_url(@order) } }
#       end

#       def close_adjustments
#         adjustments = @order.all_adjustments.not_finalized
#         adjustments.update_all(state: 'closed')
#         flash[:success] = Spree.t(:all_adjustments_closed)

#         respond_with(@order) { |format| format.html { redirect_back fallback_location: spree.admin_order_adjustments_url(@order) } }
#       end

#       def set_store
#         if @order.update(store_id: params[:order][:store_id])
#           flash[:success] = flash_message_for(@order, :successfully_updated)
#         else
#           flash[:error] = @order.errors.full_messages.join(', ')
#         end

#         redirect_to store_admin_order_url(@order)
#       end

#       private

#       def order_params
#         params[:created_by_id] = try_spree_current_user.try(:id)
#         params.permit(:created_by_id, :user_id, :store_id)
#       end

#       def load_order
#         @order = Spree::Order.includes(:adjustments).find_by!(number: params[:id])
#         authorize! action, @order
#       end

#       # Used for extensions which need to provide their own custom event links on the order details view.
#       def initialize_order_events
#         @order_events = %w{approve cancel resume}
#       end

#       def model_class
#         Spree::Order
#       end
#     end
#   end
# end

app/helpers/orders_helper.rb
module OrdersHelper
  def new_order_form
    render 'admin/orders/new_order_form'
  end

  def all_orders
    render 'admin/orders/all_orders'
  end
end

app/views/admin/orders/_all_orders.slim
.table__wrapper
  table.table.is-striped.is-narrow.is-hoverable.is-fullwidth.has-mt-24
    thead.has-bg-peach-pop-40
      tr
        th
          abbr title="Order_Date" = sort_link @search, :created_at, "Order Date"
        th 
          abbr title="Number" = sort_link(@search, :number) 
        th
          abbr title="State" = sort_link @search, :state, "State"
        th
          abbr title="Payment_State" = sort_link @search, :payment_state, "Payment State"
        th 
          abbr title="Shipment_State" = sort_link @search, :shipment_state, "Shipment State"
        th 
          abbr title="Client_Email" = sort_link @search, :email, "Email"
        th 
          abbr title="Total" = sort_link @search, :total, "Total"
    tbody
      - @orders.each do |order| 
        tr onclick="window.location='#{admin_order_path(order)}'"
          th 
            = order_time(@show_only_completed ? order.completed_at : order.created_at)
          th
            = link_to order.number, admin_order_path(order)
          th
            = order.state.downcase
          th
            - if order.payment_state 
              = order.payment_state
          th
            - if order.shipment_state 
              = order.shipment_state
          th 
            - if order.user 
              = link_to order.email, admin_customers_client_path(order.user)
            - else 
              = mail_to order.email
          th 
            = order.display_total.to_html
= paginate @orders

app/views/admin/orders/_new_order_form.html.erb
<%= form_with url: admin_orders_path, method: :post do %>

  <div id="client_autocomplete"></div>
    
<% end %>

<%= javascript_pack_tag 'client_autocomplete', 'data-turbolinks-track': 'reload' %>

app/views/admin/orders/index.html.erb
<div class="container is-fluid">
  <h1 class="title is-1 has-text-centered has-mt-24"> Orders Section </h1>
  <div class="columns">
    <div class="column is-2">
      <%= sidebar(order_sidebar_items)%>
    </div>
    <div class="column is-8 content" style="height: 150vh;">
      <%= all_orders %>
    </div>
    <div class="column">
      <div class="sticky">
        <div class="box has-mt-24 hide-mob">
          <p>Search/Scan/Filter/Notes</p>
          <br/>
          <button id="open-modal" class="button is-primary"> New Client </button>
        </div>

        <div class="box has-mt-24 hide-mob">
          <p>Search/Scan/Filter/Notes</p>
          <br/>
          <button id="open-modal" class="button is-primary"> New Order </button>
        </div>

        <div class="box has-mt-24 hide-mob">
          <p>Search/Scan/Filter/Notes</p>
          <br/>
          <button id="open-modal" class="button is-info"> New Order </button>
        </div>

      </div>
    </div>
  </div>
</div> 

app/views/admin/orders/new.slim
.container.is-fluid
  h1.title.is-1.has-text-centered.has-mt-24 New Order
  .columns
    .column.is-2
      = sidebar(order_sidebar_items)
    .column.is-8.content style="height: 150vh;"
      = new_order_form

    .column
      .sticky
        .box.hide-mob
          p Search/Scan/Filter/Notes
          br
          button.button.is-primary id="open-modal" New Client 

        .box.has-mt-24.hide-mob
          p Search/Scan/Filter/Notes
          br
          button.button.is-primary id="open-modal" New Order

        .box.has-mt-24.hide-mob
          p Search/Scan/Filter/Notes
          br
          = link_to "New Order", new_admin_order_path, class: "button is-info", id: "open-modal"